<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4xhgyqy\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4xhgyqy/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4xhgyqy.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4xhgyqy\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container4xhgyqy\appDevDebugProjectContainer([
    'container.build_hash' => '4xhgyqy',
    'container.build_id' => 'f4746f25',
    'container.build_time' => 1586914839,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4xhgyqy');
