<?php

namespace AnnonceBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByIdJoinedToCategory($annonceId)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT a, c FROM AnnonceBundle:Annonce a
            JOIN a.category c
            WHERE a.idAnnonce = :id'
            )->setParameter('id', $annonceId);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
