<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQjsel4v\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQjsel4v/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQjsel4v.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQjsel4v\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQjsel4v\appDevDebugProjectContainer([
    'container.build_hash' => 'Qjsel4v',
    'container.build_id' => '4dab4f7a',
    'container.build_time' => 1585686913,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQjsel4v');
