<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doc_doc_doc_nexmo.send_sms' shared service.

include_once $this->targetDirs[3].'\\vendor\\docdocdoc\\nexmo-bundle\\DocDocDoc\\NexmoBundle\\Provider\\ProviderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\docdocdoc\\nexmo-bundle\\DocDocDoc\\NexmoBundle\\Provider\\Sms.php';

return $this->services['doc_doc_doc_nexmo.send_sms'] = new \DocDocDoc\NexmoBundle\Provider\Sms('https://rest.nexmo.com', '534a32c6', 'n3ibI7ekYJcZlkWS');
