<?php

namespace PublicationBundle\Repository;

/**
 * reactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reactionRepository extends \Doctrine\ORM\EntityRepository
{
}
